# Generated by Django 4.1.2 on 2023-01-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'Предметы в корзине', 'verbose_name_plural': 'Предметы в корзине'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
    ]
