name: Simple Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run custom script
      run: |
        echo "Running custom script"
        python your_script.py

    - name: Final step
      run: |
        echo "All steps completed"