# Generated by Django 4.1.2 on 2022-12-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_providervariant_sizevariant_product_provider_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider_variant',
            field=models.ManyToManyField(blank=True, to='products.providervariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(blank=True, to='products.sizevariant'),
        ),
    ]
