# Generated by Django 4.1.2 on 2023-01-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купон'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товар'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображение товара'},
        ),
        migrations.AlterModelOptions(
            name='providervariant',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщик'},
        ),
        migrations.AlterModelOptions(
            name='sizevariant',
            options={'verbose_name': 'Объём покупки', 'verbose_name_plural': 'Объём покупки'},
        ),
    ]
