# Generated by Django 4.1.2 on 2023-01-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_piska'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piska',
            name='piska_size',
            field=models.CharField(max_length=50),
        ),
    ]
