# Generated by Django 4.1.2 on 2023-01-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_piska_piska_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piska',
        ),
    ]
